Zib snaq65+score
Nictiz/Nictiz-R4-zib2020 pull request #189
Opened 2021-11-10 14:42 UTC by niekvangalen

2021-11-18 14:08 UTC, LuudSlagter requested changes

2021-11-18 14:08 UTC, LuudSlagter commented on resources/zib/zib-SNAQ65+Score.xml
> +          <system value="2.16.840.1.113883.2.4.3.11.60.40.4.0.1"/>
Shouldn't the value be "urn:oid:2.16.840.1.113883.2.4.3.11.60.40.4.0.1"? Also applies to other scores.

2021-11-18 16:21 UTC, LuudSlagter approved these changes

2021-12-09 07:11 UTC, LuudSlagter commented
Validation error w.r.t. zib profile does not seem valid, as the code is present in the Dutch extension of SNOMED (checked by performing a local QA).

2021-12-09 08:00 UTC, LuudSlagter commented on resources/zib/zib-SNAQ65plusScore.xml
> +      <maxValueInteger value="5"/>
Error in the zib, see https://bits.nictiz.nl/browse/ZIB-1635.

2024-09-17 14:57 UTC, pieter-edelman-nictiz approved these changes

2024-09-17 14:57 UTC, merged