Zib name information
Nictiz/Nictiz-R4-zib2020 pull request #19
Opened 2021-02-17 13:09 UTC by ArdonToonstra

Hi Pieter/Jorn,

Hier een review verzoek voor nameinformation. Het bevat ook best wel wat tekstuele wijzigingen/aanvulligen. Soms ook op twee plekken waar ik mijn twijfels bij heb. Dit kan worden aangescherpt. Graag een eerste 'vluchtige' review hiervoor. Moet dit zelf ook nog testen met voorbeelden.

### Style - profiling guidelines
- Moved information and mappings from the extension level to the value[x] level. Note that the zib compliance test is complaining now about cardinality differences.
- HumanName.family.extensions now have the zib conceptnames as slicenames instead of the exention names.
- Usage of correct zib alias values
- Removed copied FHIR definitions and comments as this orginated  from DSTU2 and is given in the base datatype. Moreover, this increases the focus on our added comments. 
- Removed BRP mappings

-----
- Sliced HumanName.given for every zib concept that is mapped to this element. Slices are differentiated by a mandatory qualifier extension that contains a pattern. This makes the profile more explicit.
- Added mappings for the newly added zib concept 'titels' on prefix and suffix. Added documentation/implementation guidance on prefix and the root.
- Added a notion that HumanName.use is discouraged on the root and in the use element.
- Added a notion on the root that explains that if HumanName.use is used, the full name will likely break up in multiple instances of the HumanName. Systems should expect this.
- Added invariant to test for when HumanName.use is official that the name is truly official.
- Removed use in the inline examples
- Added a notion on the root that HumanName.text is encouraged to be given too.
- Added a notion on the root that we have not profiled the zib constraint to mandate a LastName.

2021-03-05 14:45 UTC, pieter-edelman-nictiz requested changes
Zie de opmerkingen mbt. de constraints. Verder ziet het er goed uit.

2021-03-08 08:29 UTC, ArdonToonstra commented on resources/zib-NameInformation.xml
> -  <mapping>
Scherp!

2021-03-08 09:47 UTC, ArdonToonstra commented on resources/zib-NameInformation.xml
> +        <source value="http://nictiz.nl/fhir/StructureDefinition/zib-NameInformation" />
Forge zet die er automatisch bij... Tis denk ik niet vekeerd gezien de definitie van het element: "A reference to the original source of the constraint, for traceability purposes." . Het gaat ook om een reference naar een StructureDefinition.
Op het eind allemaal verwijderen of laten staan zoals Forge het neerzet?

2021-03-08 09:47 UTC, ArdonToonstra commented on resources/zib-NameInformation.xml
> +        <xpath value="not(f:extension[@url='http://hl7.org/fhir/StructureDefinition/humanname-own-prefix']) or f:extension[@url='http://hl7.org/fhir/StructureDefinition/humanname-own-name']" />
Dat is nog van vroegah! Ik haal het weg.

2021-03-08 09:47 UTC, ArdonToonstra commented on resources/zib-NameInformation.xml
> +        <key value="nl-core-humanname-1" />
Ga ik aanpassen.

2021-03-08 10:29 UTC, pieter-edelman-nictiz commented on resources/zib-NameInformation.xml
> +        <source value="http://nictiz.nl/fhir/StructureDefinition/zib-NameInformation" />
Oh, als Forge dat doet, dan laten we het gewoon staan,

2021-03-08 10:48 UTC, ArdonToonstra commented on resources/zib-NameInformation.xml
> +        <key value="nl-core-humanname-1" />
Aangepast, maar wel als "zib-NameInformation-1". Dus met hoofdletters. De guidelines waren er niet heel duidelijk over. Denk dat deze manier iets leesbaarder is en sluit denk ik toch al het best aan bij wat er in de guidelines stond.

Heb het voorbeeld hier aangepast: https://informatiestandaarden.nictiz.nl/wiki/FHIR:Vprepub-1.0_FHIR_Profiling_Guidelines_R4#Miscellaneous

2021-03-09 12:05 UTC, closed without merging