Zib-AbilityToDressOneself
Nictiz/Nictiz-R4-zib2020 pull request #201
Opened 2021-11-29 09:15 UTC by Ashwin-nictiz

2021-12-09 14:32 UTC, niekvangalen requested changes

2021-12-09 14:32 UTC, niekvangalen commented on resources/zib/zib-AbilityToDressOneself.xml
> +      <path value="Observation.valueCodeableConcept" />
dit moet value[x] zijn, nog een keer resaven?

2021-12-13 09:40 UTC, Ashwin-nictiz commented on resources/zib/zib-AbilityToDressOneself.xml
> +      <path value="Observation.valueCodeableConcept" />
Fix

2021-12-13 13:08 UTC, niekvangalen approved these changes

2022-10-28 14:04 UTC, merged