Zib-AbilityToWashOneself
Nictiz/Nictiz-R4-zib2020 pull request #202
Opened 2021-11-29 10:03 UTC by Ashwin-nictiz

2021-12-09 14:33 UTC, niekvangalen requested changes

2021-12-09 14:33 UTC, niekvangalen commented on resources/zib/zib-AbilityToWashOneself.xml
> +      <path value="Observation.valueCodeableConcept" />
dit moet value[x] zijn, toch nog resaven?

2021-12-13 09:42 UTC, Ashwin-nictiz commented on resources/zib/zib-AbilityToWashOneself.xml
> +      <path value="Observation.valueCodeableConcept" />
Fixed

2021-12-13 13:07 UTC, niekvangalen approved these changes

2022-10-28 13:32 UTC, merged