Zib-PainScore
Nictiz/Nictiz-R4-zib2020 pull request #233
Opened 2022-02-02 17:12 UTC by Ashwin-nictiz

2022-02-08 15:36 UTC, niekvangalen requested changes

2022-02-08 15:36 UTC, niekvangalen commented on resources/zib/zib-PainScore.xml
> +          <code value="425401001" />
Ik denk dat het toch logischer is om hier 225908003 aan te houden, zoals in de 2017-versie ook al zo was. Deze code zit dichter bij de PainScoreValue namelijk. Zie ook de discussie in Teams.

2023-01-24 07:28 UTC, LuudSlagter approved these changes

2023-05-23 09:54 UTC, niekvangalen approved these changes

2023-05-23 10:32 UTC, LuudSlagter approved these changes

2023-07-11 19:50 UTC, pieter-edelman-nictiz commented
@LuudSlagter , zou jij nog een laatste blik op [mijn commit](https://github.com/Nictiz/Nictiz-R4-zib2020/pull/233/commits/63d4f0327f96ffcc75937ee4910365da2e9d1697) willen werpen? Ik heb de FHIRPath constraint geherformuleerd omdat ik dit wat eleganter vind, maar wellicht zit ik ernaast.
Daarnaast ook zib-PainScore-2 asls condition toegevoegd op `Observation.method`. Alhoewel `.method` strikt genomen niet genoemd wordt in de constraint zelf, slaat de constraint wel op de minimumwaarde ten gevolge van de gebruikte methode, dus dit leek me toch logisch.

2023-07-12 05:59 UTC, LuudSlagter approved these changes

2023-07-12 06:54 UTC, merged