Zib-PulseRate
Nictiz/Nictiz-R4-zib2020 pull request #344
Opened 2022-12-06 12:45 UTC by Ashwin-nictiz

2023-01-11 09:10 UTC, LuudSlagter requested changes

2023-01-11 09:10 UTC, LuudSlagter commented on resources/zib/zib-PulseRate.xml
> +    <element id="Observation">
The comment on the root that is derived from the pattern-VitalSigns profile should be changed, as the text is not correct in this case (PulseRate not being an 'official' vital sign based on core FHIR). The comment should at least indicate that we've chosen to base PulseRate on the pattern-VitalSigns profile due to it being closely related to HeartRate (and thus also for consistency), even though it is not included in the core VitalSigns profile.

2023-01-17 14:17 UTC, Ashwin-nictiz commented on resources/zib/zib-PulseRate.xml
> +    <element id="Observation.value[x]:valueQuantity">
Deleted slice and added pattern

2023-01-24 15:13 UTC, LuudSlagter commented
@niekvangalen Could you review my last commit regarding the root comment?

2023-01-24 15:18 UTC, niekvangalen approved these changes
Nice work, approved!

2023-03-09 10:50 UTC, merged