MM-5088
Nictiz/Nictiz-R4-zib2020 pull request #422
Opened 2023-11-27 14:27 UTC by LuudSlagter

2023-12-07 09:33 UTC, jduwel requested changes

2023-12-07 12:47 UTC, LuudSlagter commented on resources/zib/zib-Alert.xml
> +    <element id="Flag.extension:condition.value[x]">
Wat dom dat ik dat op die andere plekken niet heb aangepast, zeker omdat ik dat in het cio-profiel wel heb gedaan...

2023-12-07 12:49 UTC, LuudSlagter commented on resources/zib/zib-Alert.xml
> +    <element id="Flag.extension:condition.value[x]">
Verder heb ik hier geen ticket van aangemaakt, maar doorgegeven aan Astrid omdat zij nog bezig was met aanpassen van de zibs voor de prepublicatie van 2024. Volgens de Excel die we binnen CiO bijhouden, is het intussen aangepast.

2023-12-07 12:51 UTC, LuudSlagter commented on resources/zib/zib-Alert.xml
> +    </element>
Ik vind het prima om ze weg te halen; de laatste keer dat we het hierover hadden, hadden we volgens mij afgesproken om het op álle elementen te zetten die terugkomen in de constraint, zodat de constraint het makkelijkst wordt teruggevonden. Nog even ter check langs Pieter halen?

2023-12-12 21:00 UTC, pieter-edelman-nictiz commented on resources/zib/zib-Alert.xml
> +    </element>
Het _is_ dubbelop, maar dat is naar mijn idee juist een goede zaak in dit geval. Die conditions dienen om een gebruiker erop te wijzen dat een constraint van toepassing is, dus beter een keer te veel dan te weinig. In de profling guidelines staat het volgende:
>  both the element directly mentioned in the constraint as well as its child element(s) that contain the mapping to the functional model.

Dat is volgens mij hoe het hier gedaan is.

2024-01-18 15:20 UTC, jduwel approved these changes

2024-01-19 08:15 UTC, jduwel commented
Failing Loose QA, but nothing related to this PR, so bypassing check

2024-01-19 08:15 UTC, merged