Upgrade validator
Nictiz/Nictiz-R4-zib2020 pull request #431
Opened 2024-01-26 09:45 UTC by pieter-edelman-nictiz

2024-02-05 20:32 UTC, pieter-edelman-nictiz commented
@LuudSlagter , er faalt nog een check, op een ongeldige code `.system` in example nl-core-Procedure-event-01. Dit is inderdaad een ongeldige code die nog aangepast moet worden, maar je kan de rest wel vast reviewen.

2024-02-06 15:20 UTC, LuudSlagter requested changes

2024-02-07 10:42 UTC, pieter-edelman-nictiz commented on tmp.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Removed the file

2024-02-07 12:31 UTC, LuudSlagter approved these changes

2024-02-07 13:11 UTC, merged