Create validation overview
Nictiz/Nictiz-R4-zib2020 pull request #478
Opened 2024-12-16 12:40 UTC by pieter-edelman-nictiz

2024-12-16 14:09 UTC, LuudSlagter requested changes
Very nice! I've found a few typos and have added a few suggestions.

2024-12-26 16:21 UTC, ArdonToonstra reviewed
Nice approach! If HL7 NL Jira would be public, should we link to the respective tickets for all the details?

2024-12-26 16:21 UTC, ArdonToonstra commented on validation-status.md
> +
Shall we provide an overview here of the status values?

- not submitted for validation
- in progress
- validated 
- rejected

If something is rejected, the next step would be to update it to in progress once we deliver updated profiles, correct?

2024-12-26 16:21 UTC, ArdonToonstra commented on validation-status.md
> +# Maturity of these profiles
Mm, we need to be careful that this becomes a high maintenance document? I thought in the beginning we discussed with HL7 that their JIRA tickets would become public? In that case, we could link the to the JIRA ticket and leave the rejection rationale there?

2024-12-27 09:57 UTC, ArdonToonstra commented on validation-status.md
> +* Status: not submitted for validation
I am missing zib Wound.

2024-12-27 10:22 UTC, ArdonToonstra commented on validation-status.md
> +* Status: in progress
Burnwound zi ik niet staan in het HL7 Jira project. Weten we zeker dat deze is aangeleverd?

2025-01-06 09:41 UTC, pieter-edelman-nictiz commented on validation-status.md
> +# Maturity of these profiles
Yeah, it feels like we're duplicating information all over the place; there's the HL7 ticket, there's our ZIBFHIR ticket, and then we need to duplicate information here. I think this proposal is not very consistent regarding this issue, but I think sometimes it does make sense to add an extra description (e.g. the Medication profiles or the HealthcareProviderRole mapping) and sometimes a link to the issue is enough.

2025-01-06 09:54 UTC, pieter-edelman-nictiz commented on validation-status.md
> +* Status: in progress
Ja, die is wel aangeleverd. Iemand van het Validatieteam moet daar issues voor aanmaken (_wij_ kunnen het niet) 😶

2025-01-06 12:22 UTC, pieter-edelman-nictiz commented on validation-status.md
> +
Added this explanation

2025-01-06 13:52 UTC, ArdonToonstra commented on validation-status.md
> +* Status: in progress
Heb er issues voor aangemaakt!

2025-01-08 10:01 UTC, LuudSlagter approved these changes

2025-01-09 10:36 UTC, merged