zib-Refraction
Nictiz/Nictiz-R4-zib2020 pull request #71
Opened 2021-05-25 13:53 UTC by jduwel

Diff file is TODO.

2021-05-27 09:09 UTC, pieter-edelman-nictiz requested changes
The AnatomicalLocation materials shouldn't be part of the pull request. Other than that, everything looks fine!

2021-05-27 09:09 UTC, pieter-edelman-nictiz commented on resources/zib/ext-AnatomicalLocation.Laterality.xml
> +<?xml version="1.0" encoding="utf-8"?>
Shouldn't be included in the pull request

2021-05-27 09:09 UTC, pieter-edelman-nictiz commented on resources/zib/zib-AnatomicalLocation.xml
> +<?xml version="1.0" encoding="utf-8"?>
Shouldn't be included in the pull request

2021-05-27 09:09 UTC, pieter-edelman-nictiz commented on resources/nl-core/nl-core-AnatomicalLocation.xml
> +<?xml version="1.0" encoding="utf-8"?>
Shouldn't be included in the pull request.

2021-05-27 10:23 UTC, jduwel commented
1 remarkt: both Observation.code and Observation.component:readAddition.code have a mapping on SNOMED code 251718005 - https://bits.nictiz.nl/browse/ZIB-1443. Maybe one of the codes in the profile should be removed until this is resolved?

2021-05-28 08:46 UTC, ArdonToonstra commented
Made some changes to this PR. I think it is ok now!
We do have the remark stated by Jorn which we should keep track of. I changed the code in `.component.code` from 251718005 to TODO-ZIB-1443.

2023-01-09 12:17 UTC, LuudSlagter approved these changes
Laatste wijzigingen van Niek gecheckt en goedgekeurd (en nog een kleine aanvulling gedaan).

2023-01-10 08:02 UTC, pieter-edelman-nictiz approved these changes

2023-01-10 09:49 UTC, merged